/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
// Board Manual
 * https://www.st.com/resource/en/user_manual/um1974-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf
 * Reference Manual
 * https://www.st.com/resource/en/reference_manual/rm0410-stm32f76xxx-and-stm32f77xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf
 * LD2 is connected to PB7

//*/
#include <stdint.h>


int main(void)
{
	int i;
	volatile uint32_t *pRCCGPIOA = (volatile uint32_t*)(0x40023800 +0x30); // AHB1 RCC Boundary Address 0x4002 3800 - 0x4002 3BFF
	volatile uint32_t* pGPIObMode = (volatile uint32_t*)(0x40020400);// MM For Prot B
	volatile uint32_t *pGPIOState = (volatile uint32_t*)(0x40020400 +0x14);

	*pRCCGPIOA |= (0x01<<1);


	*pGPIObMode &= 0xffff3fff;
	*pGPIObMode |=0x01 <<14;


	*pGPIOState |=0x01 <<7;
//    /* Loop forever */
	while(1){
	for(i=0;i<100000;i++);
	*pGPIOState ^=0xFFFFFFFF;
	}
}
